INSERT INTO questions (idx, dataset, example_id, prompt_id, source, subject, question_number, prompt, question, choice_a, choice_b, choice_c, choice_d, answer, gold_passage, gold_idx, generated, subtopic)
VALUES
('mbe_0', 'mbe', '0', '0', 'MBE-1972-78-part2', '', '1', 'Paul, the Plaintiff in a personal injury action, called Wes as a witness to testify that Dan''s car, in which Paul had been riding. ran a red light. Wes, however, testified that Dan''s car did not run the light.', 'Paul then called Vic to testify that Dan''s car did run the light. The trial judge should rule that Vic''s testimony is', 'admissible because Paul was surprised by Wes''s testimony', 'admissible because Vic''s testimony was relevant to material issues', 'inadmissible because Paul cannot impeach his own witness', 'inadmissible because Paul is bound by the testimony of his own witness', 'B', 'Rules of evidence determine what types of evidence is admissible, and the trial court judge applies these rules to the case. Generally, to be admissible, the evidence must be relevant) and not outweighed by countervailing considerations (e.g., the evidence is unfairly prejudicial, confusing, a waste of time, privileged, or, among other reasons, based on hearsay).', 'mbe_0', 0, 'Relevancy and reasons for excluding relevant evidence'),
('mbe_1', 'mbe', '1', '0', 'MBE-1972-78-part2', '', '2', 'Paul, the Plaintiff in a personal injury action, called Wes as a witness to testify that Dan''s car, in which Paul had been riding. ran a red light. Wes, however, testified that Dan''s car did not run the light.', 'On cross-examination of Vic, Dan''s attorney asked if Vic was drunk at the time he witnessed the accident. and Vic responded, "No I have never in my life been drunk." Dan''s attorney then sought to prove by Yank that Vic was drunk on New Year''s Eve two years before the accident. The trialjudge should rule that Yank''s testimony is', 'admissible to impeach Vic by showing that he had an imperfect recollection of recent events', 'admissible to show that Vic is not the kind of person on whom one should rely for ascertaining the truth', 'inadmissible because a witness cannot be impeached by proof of specific acts of misconduct', 'inadmissible because the question of whether Vic has ever been drunk is a collateral matter', 'D', 'A matter is considered collateral if “the matter itself is not relevant in the litigation to establish a fact of consequence, i.e., not relevant for a purpose other than mere contradiction of the in-court testimony of the witness.” United States v. Beauchamp, 986 F.2d 1, 4 (1st Cir.1993) (quoting 1 McCormick on Evidence § 45 (4th ed. 1992)). Although any demonstrated inconsistency in a witness''s statement may impeach a witness''s credibility, other concerns (such as wasting time and misleading the jury) become more important when the inconsistency at *409 issue involves a statement relating to a matter that “is not relevant in the litigation to establish a fact of consequence.” Id. (quoting 1 McCormick on Evidence § 45, 169 (4th ed. 1992)).', 'mbe_1', 0, '2'),
('mbe_2', 'mbe', '2', '0', 'MBE-1972-78-part2', '', '3', 'Paul, the Plaintiff in a personal injury action, called Wes as a witness to testify that Dan''s car, in which Paul had been riding. ran a red light. Wes, however, testified that Dan''s car did not run the light.', 'Dan called Zemo as a witness and asked him if he knew Vic''s reputation for veracity in the community where Vic resided. The trialjudge should rule that this question is', 'objectionable because collateral to the issues on trial', 'objectionable because character cannot be proven by generalities', 'unobjectionable because a foundation for impeachment of Vic.', 'unobjectionable because Zemo could be expected to know Vic personally if he knew his reputation', 'C', 'Before a document may be received in evidence, it must meet a number of foundational requirements including: relevancy, authentication, the best evidence rule, and hearsay.” Hadlock v. Dir. of Revenue, 860 S.W.2d 335, 337 (Mo. banc 1993). However, “a statute may eliminate one or more of these obstacles with regard to a particular document.” Id. In the case of business records, § 490.680 allows them to be admitted despite being hearsay if
the custodian or other qualified witness testifies to [the record''s] identity and the mode of its preparation, and if it was made in the regular course of business, at or near the time of the act, condition or event, and if, in the opinion of the court, the sources of information, method and time of preparation were such as to justify its admission.
All of the requirements of § 490.680 must be satisfied for a record to be admitted as competent evidence.5 State v. Graham, 641 S.W.2d 102, 106 (Mo. banc 1982).', 'mbe_2', 0, '3'),
('mbe_3', 'mbe', '3', '1', 'MBE-1972-78-part2', '', '4', '', 'Jim watched a liquor store furtively for some time, planning to hold it up. He bought a realistic-looking toy gun for the job. One night, just before the store''s closing time, he drove to the store, opened the front door and entered. He reached in his pocket for the toy gun, but then became frightened and began to move back toward the front door. However, the shopkeeper had seen the butt of the gun. Fearing a hold up, the shopkeeper produced a gun from under the counter, pointed it at Jim, and yelled, "Stop!" Jim ran to the door and the toy gun fell from his pocket. The shopkeeper fired. The shot missed Jim, but struck and killed a passerby outside the store. A statute in the jurisdiction defines burglary as "breaking and entering any building or structure with the intent to commit a felony or to steal therein." On a charge of burglary, Jim''s best defense would be that', 'the intent required was not present', 'the liquor store was open to the public', 'he had a change of heart and withdrew before committing any crime inside the store', 'he was unsuccessful, and so at most could only be guilty of attempted burglary', 'B', 'By contrast, generic burglary''s unlawful-entry element excludes any case in which a person enters premises open to the public, no matter his intent; the generic crime requires breaking and entering or similar unlawful activity. See Brief for United States 38; LaFave § 21.1(a). So everything rests on the Government''s *276 third point: that this mismatch does not preclude applying the modified categorical approach, because it results not from a missing element but instead from an element''s overbreadth.', 'mbe_3', 0, '4'),
('mbe_7', 'mbe', '7', '3', 'MBE-1972-78-part2', '', '8', 'A water pipe burst in the basement of Supermart, a grocery store, flooding the basement and damaging cases of canned goods on the floor. The Plumbing contractor''s workmen, in repairing the leak, knocked over several stacks of canned goods in cases, denting the cans. After settling its claims against the landlord for the water leak and against the plumbing contractor for the damage done by his workmen, Supermart put the goods on special sale. Four weeks later Dotty was shopping in Supermart. Several tables in the market were covered with assorted canned foods, all of which were dirty and dented. A sign on each of the tables read: "Damaged Cans-Half Price." Dotty was having Guest for dinner that evening and purchased two dented cans of tuna, packed by Canco, from one of the tables displaying the damaged cans. Before Guest arrived, Dotty prepared a tuna casserole which she and Guest ate. Both became ill and the medical testimony established that the illness was caused by the tuna''s being unfit for consumption. The tuna consumed by Dotty and Guest came from the case that was at the top of one of the stacks knocked over by the workmen. The tuna in undamaged cans from the same Canco shipment was fit for consumption.', 'If Dotty asserts a claim against Canco based on negligence, the doctrine of res ipsa loquitur is', 'applicable, because the tuna was packed in a sealed can', 'applicable, because Canco as the packer is strictly liable', 'not applicable, because the case of tuna had been knocked over by the workmen', 'not applicable, because of the sign on the table from which Dotty purchased the tuna', 'C', 'The res ipsa loquitur doctrine “enables a jury presented only with circumstantial evidence to infer negligence simply from the fact that an event happened.” St. Paul Fire & Marine Ins. Co. v. City of New York, 907 F.2d 299, 302 (2d Cir.1990).  The criteria for applying res ipsa loquitur include
 “(1) the event must be of a kind which ordinarily does not occur in the absence of someone''s negligence; (2) it must be caused by an agency or instrumentality within the exclusive control of the defendant; (3) it must not have been due to any voluntary action or contribution on the part of the plaintiff.”
Morejon v. Rais Construction Company, 7 N.Y.3d 203, 818 N.Y.S.2d 792, 851 N.E.2d 1143, 1147 (2006) (quoting Corcoran v. Banner Super Mkt., 19 N.Y.2d 425, 280 N.Y.S.2d 385, 227 N.E.2d 304 (1967)).', 'mbe_4', 0, '8'),
('mbe_8', 'mbe', '8', '3', 'MBE-1972-78-part2', '', '9', 'A water pipe burst in the basement of Supermart, a grocery store, flooding the basement and damaging cases of canned goods on the floor. The Plumbing contractor''s workmen, in repairing the leak, knocked over several stacks of canned goods in cases, denting the cans. After settling its claims against the landlord for the water leak and against the plumbing contractor for the damage done by his workmen, Supermart put the goods on special sale. Four weeks later Dotty was shopping in Supermart. Several tables in the market were covered with assorted canned foods, all of which were dirty and dented. A sign on each of the tables read: "Damaged Cans-Half Price." Dotty was having Guest for dinner that evening and purchased two dented cans of tuna, packed by Canco, from one of the tables displaying the damaged cans. Before Guest arrived, Dotty prepared a tuna casserole which she and Guest ate. Both became ill and the medical testimony established that the illness was caused by the tuna''s being unfit for consumption. The tuna consumed by Dotty and Guest came from the case that was at the top of one of the stacks knocked over by the workmen. The tuna in undamaged cans from the same Canco shipment was fit for consumption.', 'If Guest asserts a claim against Dotty, Dotty most likely will', 'be held strictly liable in tort for serving spoiled tuna', 'be held liable only if she were negligent', 'not be held liable unless her conduct was in reckless disregard of the safety of Guest', 'not be held liable because Guest was a social visitor', 'B', 'The Indiana courts have apparently never squarely addressed the precise issue presented here.  But it has long been the rule in Indiana that the duty of care owed by a real-property owner to his social guests requires only that the host refrain from willfully, wantonly or intentionally injuring his social guests. Swanson v. Shroat, 169 Ind.App. 80, 345 N.E.2d 872 (1976); Pierce v. Walters, 152 Ind.App. 321, 283 N.E.2d 560 (1972); Fort Wayne National Bank v. Doctor, 149 Ind.App. 365, 272 N.E.2d 876 (1971).', 'mbe_5', 0, '9'),
('mbe_9', 'mbe', '9', '3', 'MBE-1972-78-part2', '', '10', 'A water pipe burst in the basement of Supermart, a grocery store, flooding the basement and damaging cases of canned goods on the floor. The Plumbing contractor''s workmen, in repairing the leak, knocked over several stacks of canned goods in cases, denting the cans. After settling its claims against the landlord for the water leak and against the plumbing contractor for the damage done by his workmen, Supermart put the goods on special sale. Four weeks later Dotty was shopping in Supermart. Several tables in the market were covered with assorted canned foods, all of which were dirty and dented. A sign on each of the tables read: "Damaged Cans-Half Price." Dotty was having Guest for dinner that evening and purchased two dented cans of tuna, packed by Canco, from one of the tables displaying the damaged cans. Before Guest arrived, Dotty prepared a tuna casserole which she and Guest ate. Both became ill and the medical testimony established that the illness was caused by the tuna''s being unfit for consumption. The tuna consumed by Dotty and Guest came from the case that was at the top of one of the stacks knocked over by the workmen. The tuna in undamaged cans from the same Canco shipment was fit for consumption.', 'If Guest asserts a claim against Supermart, the most likely result is that Guest will', 'recover on the theory of res ipsa loquitur', 'recover on the theory of strict liability in tort', 'not recover, because Supermart gave proper warning', 'not recover, because Guest was not the purchaser of the cans', 'B', 'To demonstrate strict liability, a plaintiff must show: “(1) that the defendant''s product was in a defective condition unreasonably dangerous for its intended use, (2) that the defect existed when the product left the defendant''s control, and (3) that the defect was the proximate cause of the injury sustained.” Bilotta v. Kelley Co., 346 N.W.2d 616, 623 n. 3 (Minn.1984).', 'mbe_6', 0, '10'),
('mbe_10', 'mbe', '10', '4', 'MBE-1972-78-part2', '', '11', 'Addle, who has been in the painting and contracting business for ten years and has a fine reputation, contracts to paint Boone''s barn. Boone''s barn is a standard red barn with loft. The contract has no provision regarding assignment.', 'If Addle assigns the contract to Coot, who has comparable experience and reputation, which of the following statements is correct?', 'Addle is in breach of contract.', 'Boone may refuse to accept performance by Coot.', 'Boone is required to accept performance by Coot.', 'There is a novation.', 'C', '“[e]xceptions to the rule that contracts are freely assignable are when the contract expressly provides that it is not assignable or when performance of some term of the contract involves an element of personal skill or credit.” Hurst v. West, 49 N.C.App. 598, 272 S.E.2d 378, 382–83 (1980) (citations omitted).', 'mbe_7', 0, '11'),
('mbe_11', 'mbe', '11', '4', 'MBE-1972-78-part2', '', '12', 'Addle, who has been in the painting and contracting business for ten years and has a fine reputation, contracts to paint Boone''s barn. Boone''s barn is a standard red barn with loft. The contract has no provision regarding assignment.', 'If Addle assigns the contract to Coot and thereafter Coot does not meet the contract specifications in painting Boone''s barn. Boone', 'has a cause of action against Addle for damages', 'has a cause of action only against Coot for damages', 'has a cause of action against Addle for damages only after he has first exhausted his remedies against Coot', 'does not have a cause of action against Addle for damages because he waived his rights against Addle by permitting Coot to perform the work', 'A', 'Under Massachusetts law, claims for breach of contract are generally assignable.7 Raymer v. Bay State Nat''l Bank, 384 Mass. 310, 424 N.E.2d 515, 518 (1981); see also SAPC, Inc. v. Lotus Dev. Corp., 921 F.2d 360 (1st Cir.1990).', 'mbe_8', 0, '12'),
('mbe_12', 'mbe', '12', '5', 'MBE-1972-78-part2', '', '13', 'Jackson and Brannick planned to break into a federal government office to steal food stamps. Jackson telephoned Crowley one night and asked whether Crowley wanted to buy some "hot" food stamps. Crowley, who understood that "hot" meant stolen, said: "Sure, bring them right over." Jackson and Brannick then successfully executed their scheme. That same night they delivered the food stamps to Crowley, who bought them for $500. Crowley did not ask when or by whom the stamps were stolen. All three were arrested. Jackson and Brannick entered guilty pleas in federal court to a charge of larceny in connection with the theft. Crowley was brought to trial in the state court on a charge of conspiracy to steal food stamps.', 'On the evidence stated, Crowley should be found', 'guilty, because, when a new confederate enters a conspiracy already in progress, he becomes a party to it', 'guilty, because he knowingly and willingly aided and abetted the conspiracy and is chargeable as a principal', 'not guilty, because, although Crowley knew the stamps were stolen, he neither helped to plan nor participated or assisted in the theft', 'not guilty, because Jackson and Brannick had not been convicted of or charged with conspiracy, and Crowley cannot be guilty of conspiracy by himself', 'C', 'To obtain a conspiracy conviction under § 371, “the Government must prove (1) that an agreement existed between two or more persons to commit a crime; (2) that the defendant knowingly and voluntarily joined or participated in the conspiracy; and (3) a conspirator performed an overt act in furtherance of the agreement.” United States v. Ndiaye, 434 F.3d 1270, 1294 (11th Cir.2006).', 'mbe_9', 0, '13'),
('mbe_13', 'mbe', '13', '5', 'MBE-1972-78-part2', '', '14', 'Jackson and Brannick planned to break into a federal government office to steal food stamps. Jackson telephoned Crowley one night and asked whether Crowley wanted to buy some "hot" food stamps. Crowley, who understood that "hot" meant stolen, said: "Sure, bring them right over." Jackson and Brannick then successfully executed their scheme. That same night they delivered the food stamps to Crowley, who bought them for $500. Crowley did not ask when or by whom the stamps were stolen. All three were arrested. Jackson and Brannick entered guilty pleas in federal court to a charge of larceny in connection with the theft. Crowley was brought to trial in the state court on a charge of conspiracy to steal food stamps.', 'If Jackson and Brannick are charged with conspiracy to steal the stamps in the state court, they should, on the evidence stated, be found', 'not guilty, because the charge of conspiracy is a lesser included offense in the charge of larceny', 'not guilty, because to charge them with conspiracy after their conviction of larceny would constitute double jeopardy', 'not guilty, because the state prosecution is barred by the prosecution in the federal court', 'guilty, because they planned and conspired to steal the stamps', 'D', '“This court first explicitly adopted the Pinkerton principle of vicarious liability for purposes of our state criminal law in State v. Walton, 227 Conn. 32, 630 A.2d 990 (1993). Under the Pinkerton doctrine, which, as of the date of our decision in Walton, was a recognized part of federal criminal conspiracy jurisprudence ... a conspirator may be held liable for criminal offenses committed by a coconspirator that are within the scope of the conspiracy, are in furtherance of it, and are reasonably foreseeable as a necessary or natural consequence of the conspiracy....  The rationale for the principle is that, when the conspirator [has] played a necessary part in setting in motion a discrete course of criminal conduct, he should be held responsible, within appropriate limits, for the crimes committed as *159 a natural and probable result of that course of conduct....', 'mbe_10', 0, '14'),
('mbe_14', 'mbe', '14', '6', 'MBE-1972-78-part2', '', '15', '', 'Owens contracted to sell a tract of land, Overlea, to Painter by general warranty deed. However, at the closing Painter did not carefully examine the deed and accepted a quitclaim deed without covenants of title. Painter later attempted to sell Overlea to Thompson, who refused to perform because Owens had conveyed an easement for a highway across Overlea before Painter bought the property. Painter sued Owens for damages. Which of the following arguments will most likely succeed in Owen''s defense?', 'The existence of the easement does not violate the contract.', 'The mere existence of an easement which is not being used does not give rise to a cause of action.', 'Painter''s cause of action must be based on the deed and not on the contract.', 'The proper remedy is rescission of the deed.', 'C', 'Eliker, supra, also holds that rescission is a proper remedy when the breach of contract is so substantial and fundamental as to defeat the object of the parties in making the agreement. Eliker involved a contract for construction of a house, but the non-performance was such that the house that had been bargained for was uninhabitable for all practical purposes. In **653 Gallner v. Sweep Left, Inc., 203 Neb. 169, 277 N.W.2d 689 (1979), the *497 court said that where contractual promises are mutual and dependent, the failure of one party to perform authorizes the other to rescind the contract.', 'mbe_11', 0, '15'),
('mbe_15', 'mbe', '15', '7', 'MBE-1972-78-part2', '', '16', 'Rider, a bus passenger, sued Transit Company for injuries to his back from an accident caused by Transit''s negligence. Transit denies that Rider received any injury in the accident.', 'Rider''s counsel seeks to introduce an affidavit he obtained in preparation for trial from Dr. Bond, who has since died. The affidavit avers that Dr. Bond examined Rider two days after the Transit Company accident and found him suffering from a recently incurred back injury. The judge should rule the affidavit', 'admissible as a statement of present bodily condition made to a physician', 'admissible as prior recorded testimony', 'inadmissible, because it is irrelevant', 'inadmissible, because it is hearsay, not within any exception', 'D', 'The following are not excluded by the rule against hearsay, regardless of whether the declarant is available as a witness:
(1) Present Sense Impression. A statement describing or explaining an event or condition, made while or immediately after the declarant perceived it.
(2) Excited Utterance. A statement relating to a startling event or condition, made while the declarant was under the stress of excitement that it caused.
(3) Then-Existing Mental, Emotional, or Physical Condition. A statement of the declarant’s then-existing state of mind (such as motive, intent, or plan) or emotional, sensory, or physical condition (such as mental feeling, pain, or bodily health), but not including a statement of memory or belief to prove the fact remembered or believed unless it relates to the validity or terms of the declarant’s will.
(4) Statement Made for Medical Diagnosis or Treatment. A statement that:
(A) is made for — and is reasonably pertinent to — medical diagnosis or treatment; and
(B) describes medical history; past or present symptoms or sensations; their inception; or their general cause.
(5) Recorded Recollection. A record that:
(A) is on a matter the witness once knew about but now cannot recall well enough to testify fully and accurately;
(B) was made or adopted by the witness when the matter was fresh in the witness’s memory; and
(C) accurately reflects the witness’s knowledge.
If admitted, the record may be read into evidence but may be received as an exhibit only if offered by an adverse party.
(6) Records of a Regularly Conducted Activity. A record of an act, event, condition, opinion, or diagnosis if:
(A) the record was made at or near the time by — or from information transmitted by — someone with knowledge;
(B) the record was kept in the course of a regularly conducted activity of a business, organization, occupation, or calling, whether or not for profit;
(C) making the record was a regular practice of that activity;
(D) all these conditions are shown by the testimony of the custodian or another qualified witness, or by a certification that complies with Rule 902(11) or (12) or with a statute permitting certification; and
(E) neither the opponent does not show that the source of information nor or the method or circumstances of preparation indicate a lack of trustworthiness.
(7) Absence of a Record of a Regularly Conducted Activity. Evidence that a matter is not included in a record described in paragraph (6) if:
(A) the evidence is admitted to prove that the matter did not occur or exist;
(B) a record was regularly kept for a matter of that kind; and
(C) neither the opponent does not show that the possible source of the information nor or other circumstances indicate a lack of trustworthiness.
(8) Public Records. A record or statement of a public office if:
(A) it sets out:
(i) the office’s activities;
(ii) a matter observed while under a legal duty to report, but not including, in a criminal case, a matter observed by law-enforcement personnel; or
(iii) in a civil case or against the government in a criminal case, factual findings from a legally authorized investigation; and
(B) neither the opponent does not show that the source of information nor or other circumstances indicate a lack of trustworthiness.
(9) Public Records of Vital Statistics. A record of a birth, death, or marriage, if reported to a public office in accordance with a legal duty.

(10) Absence of a Public Record. Testimony — or a certification under Rule 902 — that a diligent search failed to disclose a public record or statement if:

(A) the testimony or certification is admitted to prove that

(i) the record or statement does not exist; or

(ii) a matter did not occur or exist, if a public office regularly kept a record or statement for a matter of that kind; and

(B) in a criminal case, a prosecutor who intends to offer a certification provides written notice of that intent at least 14 days before trial, and the defendant does not object in writing within 7 days of receiving the notice — unless the court sets a different time for the notice or the objection.

(11) Records of Religious Organizations Concerning Personal or Family History. A statement of birth, legitimacy, ancestry, marriage, divorce, death, relationship by blood or marriage, or similar facts of personal or family history, contained in a regularly kept record of a religious organization.

(12) Certificates of Marriage, Baptism, and Similar Ceremonies. A statement of fact contained in a certificate:

(A) made by a person who is authorized by a religious organization or by law to perform the act certified;

(B) attesting that the person performed a marriage or similar ceremony or administered a sacrament; and

(C) purporting to have been issued at the time of the act or within a reasonable time after it.

(13) Family Records. A statement of fact about personal or family history contained in a family record, such as a Bible, genealogy, chart, engraving on a ring, inscription on a portrait, or engraving on an urn or burial marker.

(14) Records of Documents That Affect an Interest in Property. The record of a document that purports to establish or affect an interest in property if:

(A) the record is admitted to prove the content of the original recorded document, along with its signing and its delivery by each person who purports to have signed it;

(B) the record is kept in a public office; and

(C) a statute authorizes recording documents of that kind in that office.

(15) Statements in Documents That Affect an Interest in Property. A statement contained in a document that purports to establish or affect an interest in property if the matter stated was relevant to the document’s purpose — unless later dealings with the property are inconsistent with the truth of the statement or the purport of the document.

(16) Statements in Ancient Documents. A statement in a document that was prepared before January 1, 1998, and whose authenticity is established.

(17) Market Reports and Similar Commercial Publications. Market quotations, lists, directories, or other compilations that are generally relied on by the public or by persons in particular occupations.

(18) Statements in Learned Treatises, Periodicals, or Pamphlets. A statement contained in a treatise, periodical, or pamphlet if:

(A) the statement is called to the attention of an expert witness on cross-examination or relied on by the expert on direct examination; and

(B) the publication is established as a reliable authority by the expert’s admission or testimony, by another expert’s testimony, or by judicial notice.

If admitted, the statement may be read into evidence but not received as an exhibit.

(19) Reputation Concerning Personal or Family History. A reputation among a person’s family by blood, adoption, or marriage — or among a person’s associates or in the community — concerning the person’s birth, adoption, legitimacy, ancestry, marriage, divorce, death, relationship by blood, adoption, or marriage, or similar facts of personal or family history.

(20) Reputation Concerning Boundaries or General History. A reputation in a community — arising before the controversy — concerning boundaries of land in the community or customs that affect the land, or concerning general historical events important to that community, state, or nation.

(21) Reputation Concerning Character. A reputation among a person’s associates or in the community concerning the person’s character.

(22) Judgment of a Previous Conviction. Evidence of a final judgment of conviction if:

(A) the judgment was entered after a trial or guilty plea, but not a nolo contendere plea;

(B) the conviction was for a crime punishable by death or by imprisonment for more than a year;

(C) the evidence is admitted to prove any fact essential to the judgment; and

(D) when offered by the prosecutor in a criminal case for a purpose other than impeachment, the judgment was against the defendant.

The pendency of an appeal may be shown but does not affect admissibility.

(23) Judgments Involving Personal, Family, or General History, or a Boundary. A judgment that is admitted to prove a matter of personal, family, or general history, or boundaries, if the matter:

(A) was essential to the judgment; and

(B) could be proved by evidence of reputation.

(24) [Other Exceptions .] [Transferred to Rule 807.]', 'mbe_12', 0, '16'),
('mbe_16', 'mbe', '16', '7', 'MBE-1972-78-part2', '', '17', 'Rider, a bus passenger, sued Transit Company for injuries to his back from an accident caused by Transit''s negligence. Transit denies that Rider received any injury in the accident.', 'Transit Company calls Observer to testify that right after the accident, Rider told hin that he had recently suffered a recurrence of an old back injury. The judge should rule Observer''s testimony', 'admissible as an admission of a party opponent', 'admissible as a spontaneous declaration', 'inadmissible, because it is irrelevant', 'inadmissible, because it is hearsay, not within any exception', 'A', 'Admissions by party-opponents are admissible, even if they are not based on personal knowledge. Fed.R.Evid. 801(d)(2); Grace United Methodist Church v. City of Cheyenne, 451 F.3d 643, 665–67 (10th Cir.2006).', 'mbe_13', 0, '17'),
('mbe_17', 'mbe', '17', '8', 'MBE-1972-78-part2', '', '18', 'Johnston bought 100 bolts of standard blue wool, No. I quality, from McHugh. The sale contract provided that Johnston would make payment prior to inspection. The 100 bolts were shipped, and Johnston paid McHugh. Upon inspection, however, Johnston discovered that the wool was No. 2 quality. Johnston thereupon tendered back the Wool to Mc Hugh and demanded return of his payment. Mc Hugh refused on the ground that there is no difference between No. 1 quality wool and No. 2 quality wool.', 'Which of the following statements regarding the contract provision for preinspection payment is correct?', 'It constitutes an acceptance of the goods.', 'It constitutes a waiver of the buyer''s remedy of private sale in the case of nonconforming goods.', 'It does not impair a buyer''s right of inspection or his remedies.', 'It is invalid.', 'C', '1. Unless otherwise agreed and subject to subsection 3, where goods are tendered or delivered or identified to the contract for sale, the buyer has a right before payment or acceptance to inspect them at any reasonable place and time and in any reasonable manner. When the seller is required or authorized to send the goods to the buyer, the inspection may be after their arrival.
2. Expenses of inspection must be borne by the buyer but may be recovered from the seller if the goods do not conform and are rejected.
3. Unless otherwise agreed and subject to the provisions of this Article on C.I.F. contracts (section 554.2321, subsection 3), the buyer is not entitled to inspect the goods before payment of the price when the contract provides
a. for delivery “C.O.D.” or on other like terms; or
b. for payment against documents of title, except where such payment is due only after the goods are to become available for inspection.
4. A place or method of inspection fixed by the parties is presumed to be exclusive but unless otherwise expressly agreed it does not postpone identification or shift the place for delivery or for passing the risk of loss. If compliance becomes impossible, inspection shall be as provided in this section unless the place or method fixed was clearly intended as an indispensable condition failure of which avoids the contract.', 'mbe_14', 0, '18'),
('mbe_18', 'mbe', '18', '8', 'MBE-1972-78-part2', '', '19', 'Johnston bought 100 bolts of standard blue wool, No. I quality, from McHugh. The sale contract provided that Johnston would make payment prior to inspection. The 100 bolts were shipped, and Johnston paid McHugh. Upon inspection, however, Johnston discovered that the wool was No. 2 quality. Johnston thereupon tendered back the Wool to Mc Hugh and demanded return of his payment. Mc Hugh refused on the ground that there is no difference between No. 1 quality wool and No. 2 quality wool.', 'What is Johnston''s remedy because the wool was nonconforming?', 'Specific performance', 'Damages measured by the difference between the value of the goods delivered and the value of conforming goods', 'Damages measured by the price paid plus the difference between the contract price and the cost of buying substitute goods', 'None, since he waived his remedies by agreeing to pay before inspection', 'C', 'How are Compensatory Damages Calculated?
The calculation of compensatory damages depends on the type of contract that was breached and the type of loss that was incurred. Some general guidelines are:

Standard Measure. The standard measure of damages is an amount that would allow the nonbreaching party to buy a substitute for the benefit that would have been received if the contract had been performed. In cases where the cost of the substitute is speculative, the nonbreaching party may recover damages in the amount of the cost incurred in performing that party’s obligations under the contract.

Contracts for the Sale of Goods. The damages are measured by the difference between the contract price and the market price when the seller provides the goods, or when the buyer learns of the breach.', 'mbe_15', 0, '19'),
('mbe_19', 'mbe', '19', '8', 'MBE-1972-78-part2', '', '20', 'Johnston bought 100 bolts of standard blue wool, No. I quality, from McHugh. The sale contract provided that Johnston would make payment prior to inspection. The 100 bolts were shipped, and Johnston paid McHugh. Upon inspection, however, Johnston discovered that the wool was No. 2 quality. Johnston thereupon tendered back the Wool to Mc Hugh and demanded return of his payment. Mc Hugh refused on the ground that there is no difference between No. 1 quality wool and No. 2 quality wool.', 'Can Johnston resell the wool?', 'Yes, in a private sale.', 'Yes, in a private sale but only after giving Mc Hugh reasonable notice of his intention to resell.', 'Yes, but only at a public sale.', 'No.', 'B', 'Under this section the seller may resell the goods after any breach by the buyer. Thus, an anticipatory repudiation by the buyer gives rise to any of the seller’s remedies for breach, and to the right of resale.', 'mbe_16', 0, '20'),
('mbe_20', 'mbe', '20', '9', 'MBE-1972-78-part2', '', '21', '', 'Lord leased a warehouse building and the lot on which it stood to Taylor for a term of ten years. The lease contained a clause prohibiting Taylor from subletting his interest. Can Taylor assign his interest under the lease?', 'Yes, because restraints on alier ation of land are strictly construed.', 'Yes, because disabling restraints on alienation of land are invalid.', 'No, because the term "subletting" includes "assignment" when the term is employed in a lease.', 'No. because, even in the absence of an express prohibition on assignment, a tenant may not assign without the landlord''s permission.', 'A', 'A restraint on alienation, in the law of real property, is a clause used in the conveyance of real property that seeks to prohibit the recipient from selling or otherwise transferring their interest in the property. Under the common law such restraints are void as against the public policy of allowing landowners to freely dispose of their property. Perhaps the ultimate restraint on alienation was the fee tail, a form of ownership which required that property be passed down in the same family from generation to generation, which has also been widely abolished', 'mbe_17', 0, '21'),
('mbe_21', 'mbe', '21', '10', 'MBE-1972-78-part2', '', '22', '', 'Diner, a drive-in hamburger and ice cream stand, recently opened for business in the suburban town of Little City. Diner''s business hours are from 9:00 a.m. to midnight. It is in an area that for fifteen years has been zoned for small retail businesses, apartment buildings, and one- and two-family residences. The zoning code specifies that "small retail businesses" include "businesses where food and drink are dispensed for consumption on the premises." Diner was the first drive-in in Little City. For seven years Mr. and Mrs. Householder have owned and lived in their single-family residence, which is across the street from Diner. On opening day a brass band played in the parking lot of Diner until midnight, and the noise of cars and the unusual activity as a result of the new business prevented the Householders from getting to sleep until well after midnight, long after their usual time. Diner is heavily patronized during the day and night by high school students. The noise of cars, the lights of the cars, the lights illuminating the parking lot at Diner, and the noise from the loudspeaker of the ordering system prevented the Householders from sleeping before midnight. Paper cups, napkins, and other items from the drive-in are regularly blown into the Householders'' front yard by the prevailing wind. The traffic to and from Diner is so heavy on the street in front of their house that the Householders are afraid to allow their small children to play in the front yard. The Householders have asserted a claim against Diner based on private nuisance. The most likely effect of the fact that Householders were in the area before Diner is that it', 'requires that the Householders'' interest be given priority', 'is irrelevant because of the zoning ordinance', 'is irrelevant because conforming economic uses are given priority', 'is some, but not controlling, evidence', 'D', 'Nuisance Defenses
There are several defenses available to those accused of creating a nuisance. One important defense is called ‘coming to the nuisance’. It applies when the harmful activity was operating before the plaintiffs acquired the property impacted by the nuisance. If the owners were aware of the nuisance-creating activity at the time they purchased the property, the defendant may invoke the defense of ‘coming to the nuisance’. This defense effectively argues that the plaintiffs knew what they were getting themselves into and assumed the risk of harm. While in the past, ‘coming to the nuisance’ was considered an absolute defense, today it is a factor that the courts will consider in determining whether the plaintiffs may recover for nuisance.[4] An example of this manifested in Foster v. Preston Mill Co.,[5] wherein blasting from a nearby timber farm caused minks to panic and attack each other. As the farm existed before the ranch housing the minks, there was no liability for nuisance.', 'mbe_18', 0, '22'),
('mbe_22', 'mbe', '22', '11', 'MBE-1972-78-part2', '', '23', 'Jack and Paul planned to hold up a bank. They drove to the bank in Jack''s car. Jack entered while Paul remained as lookout in the car. After a few moments, Paul panicked and drove off. Jack looked over the various tellers, approached one and wispered nervously, "Just hand over the cash. Don''t look around, don''t make a false move-or it''s your life." The teller looked at the fidgeting Jack, laughed, flipped him a dollar bill and said, "Go on, beat it." Flustered, Jack grabbed the dollar and left. Soon after leaving the scene, Paul was stopped by the police for speeding. Noting his nervous condition, the police asked Paul if they might search the car. Paul agreed. The search turned up heroin concealed in the lid of the trunk.', 'Paul''s best defense to a charge of robbery would be that', 'Jack alone entered the bank', 'Paul withdrew before commission of the crime when he fled the scene', 'Paul had no knowledge of what Jack whispered to the teller', 'the teller was not placed in fear by Jack', 'D', '“Robbery” is the “[f]elonious taking of ... [any] article of value, in the possession of another, from his person or immediate presence, and against his will, accomplished by means of force or fear.” Id. at 1193 (emphasis added) (citations omitted). Finally, the act of “pillaging” is the “forcible taking of private property by an invading or conquering army from the enemy''s subjects.” Id. at 1033 (emphasis added).', 'mbe_19', 0, '23'),
('mbe_23', 'mbe', '23', '11', 'MBE-1972-78-part2', '', '24', 'Jack and Paul planned to hold up a bank. They drove to the bank in Jack''s car. Jack entered while Paul remained as lookout in the car. After a few moments, Paul panicked and drove off. Jack looked over the various tellers, approached one and wispered nervously, "Just hand over the cash. Don''t look around, don''t make a false move-or it''s your life." The teller looked at the fidgeting Jack, laughed, flipped him a dollar bill and said, "Go on, beat it." Flustered, Jack grabbed the dollar and left. Soon after leaving the scene, Paul was stopped by the police for speeding. Noting his nervous condition, the police asked Paul if they might search the car. Paul agreed. The search turned up heroin concealed in the lid of the trunk.', 'The prosecution''s best argument to sustain the validity of the search of Jack''s car would be that', 'the search was reasonable under the circumstances, including Paul''s nervous condition', 'the search was incident to a valid arrest', 'Paul had, under the circumstances, sufficient standing and authority to consent to the search', 'exigent circumstances, including the inherent mobility of a car, justified the search', 'C', 'The Fourth Amendment provides that “[t]he right of the people ... against unreasonable searches and seizures, shall not be violated ....” U.S. Const. Amend. IV. And it is axiomatic that a warrantless search is “ ‘per se unreasonable’ unless it falls within one of the ‘specifically established and well-delineated exceptions’ to the warrant requirement.” United States v. Simons, 206 F.3d 392, 399-400 (4th Cir. 2000) (quoting Katz v. United States, 389 U.S. 347, 357, 88 S.Ct. 507, 19 L.Ed.2d 576 (1967) ). One such exception occurs when there is valid consent to the search. Fernandez v. California, 571 U.S. 292, 298, 134 S.Ct. 1126, 188 L.Ed.2d 25 (2014). Fourth Circuit and Supreme Court precedent make clear that consent to search is valid for Fourth Amendment purposes if it is (1) “knowing and voluntary,”3 and (2) given by one with authority to consent.', 'mbe_20', 0, '24'),
('mbe_24', 'mbe', '24', '12', 'MBE-1972-78-part2', '', '25', '', 'Pace sues Def Company for injuries suffered when Pace''s car collided with Def Company''s truck. Def''s general manager prepared a report of the accident at the request of the company''s attorney in preparation for the trial, and delivered the report to the attorney. Pace demands that the report be produced. Will production of the report be required?', 'Yes, because business reports are not generally privileged.', 'No, because it is a privileged communication from client to the attorney.', 'No, because such reports contain hearsay.', 'No, because such reports are self-serving.', 'B', 'The attorney-client privilege protects communications made in confidence by a client and a client''s employees to an attorney, acting as an attorney, for the purpose of obtaining legal advice. Sandra T.E. v. South Berwyn School Dist. 100, 600 F.3d 612, 618 (7th Cir.2010). The analysis is “(1) whether ‘legal advice of any kind [was] sought ... from a professional legal adviser in his capacity as such’; and (2) whether the communication was ‘relat[ed] to that purpose’ and ‘made in confidence ... by the client.’ ” Id. (citation omitted). “[T]he attorney-client privilege protects not only the attorney-client relationship in imminent or ongoing litigation but also the broader attorney-client relationship outside the litigation context.” Id. at 621.', 'mbe_21', 0, '25'),
('mbe_25', 'mbe', '25', '13', 'MBE-1972-78-part2', '', '26', '', 'The following facts concern a tract of land in a state which follows general United States law. Each instrument is in proper form, recorded, marital property rights were waived when necessary, and each person named was adult and competent at the time of the named transaction. 1. In 1940 Oleg, the owner, conveyed his interest in fee simple "to my brothers Bob and Bill, their heirs and assigns as joint tenants with right of survivorship." 2. In 1950 Bob died, devising his interest to his only child, "Charles, for life, and then to Charles''s son, Sam, for life, and then to Sam''s children, their heirs and assigns." 3. In 1970 Bill died, devising his interest "to my friend, Frank, his heirs and assigns." 4. In 1972 Frank conveyed by quitclaim deed "to Paul, his heirs and assigns whatever right, title and interest I own." Paul has never married. Paul has contracted to convey marketable record title in the land to Patrick. Can Paul do so?', 'Yes, without joinder of any other person in the conveyance.', 'Yes, if Charles, Sam, and Sam''s only child (Gene, aged 25) will join in the conveyance.', 'No, regardless of who joins in the conveyance, because Sam may have additional children whose interests cannot be defeated.', 'No, regardless of who joins in the conveyance, because a title acquired by quitclaim deed is impliedly unmerchantable.', 'A', 'In the instant case the husband had been dead for several months at the time the wife joined in the conveyance, and he could not, therefore, have consented to her subsequent execution of the same. When he died on April 1, 1948, he was the absolute owner of the land in question, because of the invalidity of his former deed of conveyance thereof without the signature of his wife, and, therefore, the rights of the complainants in the present case had intervented long prior to her signing and acknowledging the deed. This fact distinguishes Howell v. Hill from the case at bar. Even though the wife of John Brassel may have been willing that the homestead be sold on October 24, 1942, the time at which the contemporaneous assent of the husband and wife must exist is the time when the deed is finally executed by her joinder therein. In other words, the deed is void as to the owner of the homestead who has executed a deed to the same until the other spouse joins therein with the contemporaneous assent of both.  Consequently, there can be no joinder by the wife in the execution of a conveyance of the homestead by the husband unless she executes the conveyance during his lifetime, and with his consent.', 'mbe_22', 0, '26'),
('mbe_26', 'mbe', '26', '14', 'MBE-1972-78-part2', '', '27', 'Peter was rowing a boat on a mountain lake when a storm suddenly arose. Fearful that the boat might sink, Peter rowed to a boat dock on shore and tied the boat to the dock. The shore property and dock were the private property of Owner. While the boat was tied at the dock, Owner came down and ordered Peter to remove the boat, because the action of the waves was causing the boat to rub against a bumper on the dock. When Peter refused, Owner untied the boat and cast it adrift. The boat sank. Peter was wearing a pair of swimming trunks nothing else. He had a pair of shoes and a parka in the boat, but they were lost when Owner set it adrift. Peter was staying at a cabin one mile from Owner''s property. The only land routes back were a short rocky trail that was dangerous during the storm, and a 15-mile road around the lake. The storm continued with heavy rain and hail, and Peter having informed Owner of the location of his cabin, asked Owner to take him back there in Owner''s car. Owner said, " You got here by yourself and you''ll have to get back home yourself." After one hour the storm stopped, and Peter walked home over the trail.', 'A necessary element in determining if Peter is liable for a trespass is whether', 'Owner had clearly posted his property with a sign indicating that it was private property', 'Peter knew that the property belonged to a private person', 'Peter had reasonable grounds to believe the property belonged to a private person', 'Peter had reasonable grounds to believe his boat might be swamped and sink', 'D', 'To state a claim for trespass, a plaintiff must establish “(1) an interference with a possessory interest in his property; (2) through the defendant’s physical act or force against that property; (3) which was executed without [the plaintiff’s] consent.” Mitchell v. Baltimore Sun. Co., 883 A.2d 1008, 1014 (Md. Ct. Spec. App. 2005). The alleged trespasser does not need to cause any actual damage to the property; nominal damages may be recovered for any unauthorized entry. Tyler v. Cedar Island Club, 122 A. 38, 39 (Md. 1923).', 'mbe_23', 0, '27'),
('mbe_27', 'mbe', '27', '14', 'MBE-1972-78-part2', '', '28', 'Peter was rowing a boat on a mountain lake when a storm suddenly arose. Fearful that the boat might sink, Peter rowed to a boat dock on shore and tied the boat to the dock. The shore property and dock were the private property of Owner. While the boat was tied at the dock, Owner came down and ordered Peter to remove the boat, because the action of the waves was causing the boat to rub against a bumper on the dock. When Peter refused, Owner untied the boat and cast it adrift. The boat sank. Peter was wearing a pair of swimming trunks nothing else. He had a pair of shoes and a parka in the boat, but they were lost when Owner set it adrift. Peter was staying at a cabin one mile from Owner''s property. The only land routes back were a short rocky trail that was dangerous during the storm, and a 15-mile road around the lake. The storm continued with heavy rain and hail, and Peter having informed Owner of the location of his cabin, asked Owner to take him back there in Owner''s car. Owner said, " You got here by yourself and you''ll have to get back home yourself." After one hour the storm stopped, and Peter walked home over the trail.', 'If Peter asserts a claim against Owner for loss of the boat, the most likely result is that Owner will', 'have no defense under the circumstances', 'prevail because Peter was a trespasser ab initio', 'prevail because the boat might have damaged the dock', 'prevail because Peter became a trespasser when he refused to remove the boat', 'A', 'A constable who seizes the property of a defendant under an execution, and refuses to permit such defendant to select, and to have appraised for him property to the amount of $300 under the Act of 1849, the defendant demanding, and being entitled to the benefit of the exemption, becomes liable as a trespasser ab initio.', 'mbe_24', 0, '28')
ON CONFLICT (idx) DO NOTHING;
