INSERT INTO question_explanations (question_id, correct_answer, choice_a_explanation, choice_b_explanation, choice_c_explanation, choice_d_explanation, subtopic, ai_explanation, created_at, updated_at)
VALUES
('547', 'B', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL),
('548', 'B', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL),
('549', 'B', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL),
('550', 'B', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL),
('551', 'C', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL),
('552', 'C', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL),
('553', 'C', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL),
('554', 'C', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL),
('555', 'D', 'Incorrect.', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', NULL, 'Hearsay = TOMA | MIMIC for prior bad acts: Motive, Intent, Mistake, Identity, Common plan | Exceptions: present sense, excited utterance, state of mind.', '2026-02-05 02:10:17', NULL),
('556', 'D', 'Incorrect.', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', NULL, 'SMJ: Federal question, Diversity | PJ: Minimum contacts | Erie: state substantive, federal procedural.', '2026-02-05 02:10:17', NULL)
ON CONFLICT (question_id) DO NOTHING;
