INSERT INTO question_explanations (question_id, correct_answer, choice_a_explanation, choice_b_explanation, choice_c_explanation, choice_d_explanation, subtopic, ai_explanation, created_at, updated_at)
VALUES
('127', 'B', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL),
('128', 'C', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL),
('129', 'B', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL),
('130', 'D', 'Incorrect.', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL),
('131', 'C', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL),
('132', 'B', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL),
('133', 'B', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL),
('134', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL),
('135', 'D', 'Incorrect.', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL),
('136', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL)
ON CONFLICT (question_id) DO NOTHING;
