INSERT INTO question_explanations (question_id, correct_answer, choice_a_explanation, choice_b_explanation, choice_c_explanation, choice_d_explanation, subtopic, ai_explanation, created_at, updated_at)
VALUES
('667', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, '4th ESCAPIST: Exigent, Search incident, Consent, Auto, Plain view, Inventory, Stop & frisk, Terry | Miranda = custody + interrogation.', '2026-02-05 02:10:17', NULL),
('668', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, '4th ESCAPIST: Exigent, Search incident, Consent, Auto, Plain view, Inventory, Stop & frisk, Terry | Miranda = custody + interrogation.', '2026-02-05 02:10:17', NULL),
('669', 'D', 'Incorrect.', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', NULL, '4th ESCAPIST: Exigent, Search incident, Consent, Auto, Plain view, Inventory, Stop & frisk, Terry | Miranda = custody + interrogation.', '2026-02-05 02:10:17', NULL),
('670', 'D', 'Incorrect.', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', NULL, '4th ESCAPIST: Exigent, Search incident, Consent, Auto, Plain view, Inventory, Stop & frisk, Terry | Miranda = custody + interrogation.', '2026-02-05 02:10:17', NULL),
('671', 'B', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', NULL, '4th ESCAPIST: Exigent, Search incident, Consent, Auto, Plain view, Inventory, Stop & frisk, Terry | Miranda = custody + interrogation.', '2026-02-05 02:10:17', NULL),
('672', 'D', 'Incorrect.', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', NULL, '4th ESCAPIST: Exigent, Search incident, Consent, Auto, Plain view, Inventory, Stop & frisk, Terry | Miranda = custody + interrogation.', '2026-02-05 02:10:17', NULL),
('673', 'C', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', NULL, '4th ESCAPIST: Exigent, Search incident, Consent, Auto, Plain view, Inventory, Stop & frisk, Terry | Miranda = custody + interrogation.', '2026-02-05 02:10:17', NULL),
('674', 'C', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', NULL, '4th ESCAPIST: Exigent, Search incident, Consent, Auto, Plain view, Inventory, Stop & frisk, Terry | Miranda = custody + interrogation.', '2026-02-05 02:10:17', NULL),
('675', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, '4th ESCAPIST: Exigent, Search incident, Consent, Auto, Plain view, Inventory, Stop & frisk, Terry | Miranda = custody + interrogation.', '2026-02-05 02:10:17', NULL),
('676', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, '4th ESCAPIST: Exigent, Search incident, Consent, Auto, Plain view, Inventory, Stop & frisk, Terry | Miranda = custody + interrogation.', '2026-02-05 02:10:17', NULL)
ON CONFLICT (question_id) DO NOTHING;
