INSERT INTO question_explanations (question_id, correct_answer, choice_a_explanation, choice_b_explanation, choice_c_explanation, choice_d_explanation, subtopic, ai_explanation, created_at, updated_at)
VALUES
('487', 'D', 'Incorrect.', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', NULL, 'Elements: Actus reus + Mens rea + Causation + Concurrence | BARRK: Burglary, Arson, Robbery, Rape, Kidnapping | Mens rea: Purpose > Knowledge > Recklessness > Negligence.', '2026-02-05 02:10:17', NULL),
('488', 'C', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', NULL, 'SMJ: Federal question, Diversity | PJ: Minimum contacts | Erie: state substantive, federal procedural.', '2026-02-05 02:10:17', NULL),
('489', 'C', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', NULL, 'SMJ: Federal question, Diversity | PJ: Minimum contacts | Erie: state substantive, federal procedural.', '2026-02-05 02:10:17', NULL),
('490', 'B', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', NULL, 'SMJ: Federal question, Diversity | PJ: Minimum contacts | Erie: state substantive, federal procedural.', '2026-02-05 02:10:17', NULL),
('491', 'D', 'Incorrect.', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', NULL, 'SMJ: Federal question, Diversity | PJ: Minimum contacts | Erie: state substantive, federal procedural.', '2026-02-05 02:10:17', NULL),
('492', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, 'FRAMEWORK: State action → Provision → Scrutiny → Survives? | CAMPER for 1st Amendment | SSR for Equal Protection: Strict (race), Intermediate (gender), Rational (economic).', '2026-02-05 02:10:17', NULL),
('493', 'B', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', NULL, 'FRAMEWORK: State action → Provision → Scrutiny → Survives? | CAMPER for 1st Amendment | SSR for Equal Protection: Strict (race), Intermediate (gender), Rational (economic).', '2026-02-05 02:10:17', NULL),
('494', 'C', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', NULL, 'SMJ: Federal question, Diversity | PJ: Minimum contacts | Erie: state substantive, federal procedural.', '2026-02-05 02:10:17', NULL),
('495', 'B', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', NULL, 'SMJ: Federal question, Diversity | PJ: Minimum contacts | Erie: state substantive, federal procedural.', '2026-02-05 02:10:17', NULL),
('496', 'B', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', NULL, 'SMJ: Federal question, Diversity | PJ: Minimum contacts | Erie: state substantive, federal procedural.', '2026-02-05 02:10:17', NULL)
ON CONFLICT (question_id) DO NOTHING;
