INSERT INTO question_explanations (question_id, correct_answer, choice_a_explanation, choice_b_explanation, choice_c_explanation, choice_d_explanation, subtopic, ai_explanation, created_at, updated_at)
VALUES
('537', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, 'Estates: Fee simple > Defeasible > Life | Future: Reversion (grantor), Remainder (3rd party) | Recording: Race, Notice, Race-Notice.', '2026-02-05 02:10:17', NULL),
('538', 'C', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', NULL, 'Estates: Fee simple > Defeasible > Life | Future: Reversion (grantor), Remainder (3rd party) | Recording: Race, Notice, Race-Notice.', '2026-02-05 02:10:17', NULL),
('539', 'D', 'Incorrect.', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', NULL, 'SMJ: Federal question, Diversity | PJ: Minimum contacts | Erie: state substantive, federal procedural.', '2026-02-05 02:10:17', NULL),
('540', 'B', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', NULL, 'Hearsay = TOMA | MIMIC for prior bad acts: Motive, Intent, Mistake, Identity, Common plan | Exceptions: present sense, excited utterance, state of mind.', '2026-02-05 02:10:17', NULL),
('541', 'D', 'Incorrect.', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', NULL, 'Hearsay = TOMA | MIMIC for prior bad acts: Motive, Intent, Mistake, Identity, Common plan | Exceptions: present sense, excited utterance, state of mind.', '2026-02-05 02:10:17', NULL),
('542', 'C', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', NULL, 'Hearsay = TOMA | MIMIC for prior bad acts: Motive, Intent, Mistake, Identity, Common plan | Exceptions: present sense, excited utterance, state of mind.', '2026-02-05 02:10:17', NULL),
('543', 'B', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', NULL, 'Hearsay = TOMA | MIMIC for prior bad acts: Motive, Intent, Mistake, Identity, Common plan | Exceptions: present sense, excited utterance, state of mind.', '2026-02-05 02:10:17', NULL),
('544', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, 'SMJ: Federal question, Diversity | PJ: Minimum contacts | Erie: state substantive, federal procedural.', '2026-02-05 02:10:17', NULL),
('545', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, 'SMJ: Federal question, Diversity | PJ: Minimum contacts | Erie: state substantive, federal procedural.', '2026-02-05 02:10:17', NULL),
('546', 'D', 'Incorrect.', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', NULL, 'SMJ: Federal question, Diversity | PJ: Minimum contacts | Erie: state substantive, federal procedural.', '2026-02-05 02:10:17', NULL)
ON CONFLICT (question_id) DO NOTHING;
