INSERT INTO question_explanations (question_id, correct_answer, choice_a_explanation, choice_b_explanation, choice_c_explanation, choice_d_explanation, subtopic, ai_explanation, created_at, updated_at)
VALUES
('647', 'C', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL),
('648', 'D', 'Incorrect.', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', NULL, 'FRAMEWORK: State action → Provision → Scrutiny → Survives? | CAMPER for 1st Amendment | SSR for Equal Protection: Strict (race), Intermediate (gender), Rational (economic).', '2026-02-05 02:10:17', NULL),
('649', 'C', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', NULL, '4th ESCAPIST: Exigent, Search incident, Consent, Auto, Plain view, Inventory, Stop & frisk, Terry | Miranda = custody + interrogation.', '2026-02-05 02:10:17', NULL),
('650', 'B', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', NULL, '4th ESCAPIST: Exigent, Search incident, Consent, Auto, Plain view, Inventory, Stop & frisk, Terry | Miranda = custody + interrogation.', '2026-02-05 02:10:17', NULL),
('651', 'D', 'Incorrect.', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', NULL, '4th ESCAPIST: Exigent, Search incident, Consent, Auto, Plain view, Inventory, Stop & frisk, Terry | Miranda = custody + interrogation.', '2026-02-05 02:10:17', NULL),
('652', 'D', 'Incorrect.', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', NULL, '4th ESCAPIST: Exigent, Search incident, Consent, Auto, Plain view, Inventory, Stop & frisk, Terry | Miranda = custody + interrogation.', '2026-02-05 02:10:17', NULL),
('653', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, '4th ESCAPIST: Exigent, Search incident, Consent, Auto, Plain view, Inventory, Stop & frisk, Terry | Miranda = custody + interrogation.', '2026-02-05 02:10:17', NULL),
('654', 'C', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', NULL, 'Elements: Actus reus + Mens rea + Causation + Concurrence | BARRK: Burglary, Arson, Robbery, Rape, Kidnapping | Mens rea: Purpose > Knowledge > Recklessness > Negligence.', '2026-02-05 02:10:17', NULL),
('655', 'B', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', NULL, 'Elements: Actus reus + Mens rea + Causation + Concurrence | BARRK: Burglary, Arson, Robbery, Rape, Kidnapping | Mens rea: Purpose > Knowledge > Recklessness > Negligence.', '2026-02-05 02:10:17', NULL),
('656', 'C', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL)
ON CONFLICT (question_id) DO NOTHING;
