INSERT INTO question_explanations (question_id, correct_answer, choice_a_explanation, choice_b_explanation, choice_c_explanation, choice_d_explanation, subtopic, ai_explanation, created_at, updated_at)
VALUES
('327', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, 'DBCD: Duty, Breach, Causation, Damages | Strict: dangerous activities, wild animals, products | BAFTIC: Battery, Assault, False imprisonment, Trespass, IIED, Conversion.', '2026-02-05 02:10:17', NULL),
('328', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, 'DBCD: Duty, Breach, Causation, Damages | Strict: dangerous activities, wild animals, products | BAFTIC: Battery, Assault, False imprisonment, Trespass, IIED, Conversion.', '2026-02-05 02:10:17', NULL),
('329', 'D', 'Incorrect.', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', NULL, 'DBCD: Duty, Breach, Causation, Damages | Strict: dangerous activities, wild animals, products | BAFTIC: Battery, Assault, False imprisonment, Trespass, IIED, Conversion.', '2026-02-05 02:10:17', NULL),
('330', 'C', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', NULL, 'DBCD: Duty, Breach, Causation, Damages | Strict: dangerous activities, wild animals, products | BAFTIC: Battery, Assault, False imprisonment, Trespass, IIED, Conversion.', '2026-02-05 02:10:17', NULL),
('331', 'C', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', NULL, 'DBCD: Duty, Breach, Causation, Damages | Strict: dangerous activities, wild animals, products | BAFTIC: Battery, Assault, False imprisonment, Trespass, IIED, Conversion.', '2026-02-05 02:10:17', NULL),
('332', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL),
('333', 'C', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL),
('334', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL),
('335', 'B', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', NULL, 'Estates: Fee simple > Defeasible > Life | Future: Reversion (grantor), Remainder (3rd party) | Recording: Race, Notice, Race-Notice.', '2026-02-05 02:10:17', NULL),
('336', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, 'Estates: Fee simple > Defeasible > Life | Future: Reversion (grantor), Remainder (3rd party) | Recording: Race, Notice, Race-Notice.', '2026-02-05 02:10:17', NULL)
ON CONFLICT (question_id) DO NOTHING;
