INSERT INTO question_explanations (question_id, correct_answer, choice_a_explanation, choice_b_explanation, choice_c_explanation, choice_d_explanation, subtopic, ai_explanation, created_at, updated_at)
VALUES
('27', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, 'Hearsay = TOMA | MIMIC for prior bad acts: Motive, Intent, Mistake, Identity, Common plan | Exceptions: present sense, excited utterance, state of mind.', '2026-02-05 02:10:17', NULL),
('28', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL),
('29', 'B', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', NULL, 'DBCD: Duty, Breach, Causation, Damages | Strict: dangerous activities, wild animals, products | BAFTIC: Battery, Assault, False imprisonment, Trespass, IIED, Conversion.', '2026-02-05 02:10:17', NULL),
('30', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, 'Elements: Actus reus + Mens rea + Causation + Concurrence | BARRK: Burglary, Arson, Robbery, Rape, Kidnapping | Mens rea: Purpose > Knowledge > Recklessness > Negligence.', '2026-02-05 02:10:17', NULL),
('31', 'D', 'Incorrect.', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', NULL, 'Estates: Fee simple > Defeasible > Life | Future: Reversion (grantor), Remainder (3rd party) | Recording: Race, Notice, Race-Notice.', '2026-02-05 02:10:17', NULL),
('32', 'B', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', NULL, 'Estates: Fee simple > Defeasible > Life | Future: Reversion (grantor), Remainder (3rd party) | Recording: Race, Notice, Race-Notice.', '2026-02-05 02:10:17', NULL),
('33', 'D', 'Incorrect.', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', NULL, 'Estates: Fee simple > Defeasible > Life | Future: Reversion (grantor), Remainder (3rd party) | Recording: Race, Notice, Race-Notice.', '2026-02-05 02:10:17', NULL),
('34', 'D', 'Incorrect.', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL),
('35', 'B', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', NULL, 'DBCD: Duty, Breach, Causation, Damages | Strict: dangerous activities, wild animals, products | BAFTIC: Battery, Assault, False imprisonment, Trespass, IIED, Conversion.', '2026-02-05 02:10:17', NULL),
('36', 'D', 'Incorrect.', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', NULL, 'DBCD: Duty, Breach, Causation, Damages | Strict: dangerous activities, wild animals, products | BAFTIC: Battery, Assault, False imprisonment, Trespass, IIED, Conversion.', '2026-02-05 02:10:17', NULL)
ON CONFLICT (question_id) DO NOTHING;
