INSERT INTO question_explanations (question_id, correct_answer, choice_a_explanation, choice_b_explanation, choice_c_explanation, choice_d_explanation, subtopic, ai_explanation, created_at, updated_at)
VALUES
('497', 'B', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', NULL, 'SMJ: Federal question, Diversity | PJ: Minimum contacts | Erie: state substantive, federal procedural.', '2026-02-05 02:10:17', NULL),
('498', 'D', 'Incorrect.', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', NULL, 'SMJ: Federal question, Diversity | PJ: Minimum contacts | Erie: state substantive, federal procedural.', '2026-02-05 02:10:17', NULL),
('499', 'D', 'Incorrect.', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', NULL, 'SMJ: Federal question, Diversity | PJ: Minimum contacts | Erie: state substantive, federal procedural.', '2026-02-05 02:10:17', NULL),
('500', 'D', 'Incorrect.', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', NULL, 'SMJ: Federal question, Diversity | PJ: Minimum contacts | Erie: state substantive, federal procedural.', '2026-02-05 02:10:17', NULL),
('501', 'C', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', NULL, 'SMJ: Federal question, Diversity | PJ: Minimum contacts | Erie: state substantive, federal procedural.', '2026-02-05 02:10:17', NULL),
('502', 'B', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', NULL, 'SMJ: Federal question, Diversity | PJ: Minimum contacts | Erie: state substantive, federal procedural.', '2026-02-05 02:10:17', NULL),
('503', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, 'Estates: Fee simple > Defeasible > Life | Future: Reversion (grantor), Remainder (3rd party) | Recording: Race, Notice, Race-Notice.', '2026-02-05 02:10:17', NULL),
('504', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL),
('505', 'C', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL),
('506', 'D', 'Incorrect.', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', NULL, 'Estates: Fee simple > Defeasible > Life | Future: Reversion (grantor), Remainder (3rd party) | Recording: Race, Notice, Race-Notice.', '2026-02-05 02:10:17', NULL)
ON CONFLICT (question_id) DO NOTHING;
