INSERT INTO question_explanations (question_id, correct_answer, choice_a_explanation, choice_b_explanation, choice_c_explanation, choice_d_explanation, subtopic, ai_explanation, created_at, updated_at)
VALUES
('307', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, 'Estates: Fee simple > Defeasible > Life | Future: Reversion (grantor), Remainder (3rd party) | Recording: Race, Notice, Race-Notice.', '2026-02-05 02:10:17', NULL),
('308', 'D', 'Incorrect.', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', NULL, 'Estates: Fee simple > Defeasible > Life | Future: Reversion (grantor), Remainder (3rd party) | Recording: Race, Notice, Race-Notice.', '2026-02-05 02:10:17', NULL),
('309', 'B', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', NULL, 'Estates: Fee simple > Defeasible > Life | Future: Reversion (grantor), Remainder (3rd party) | Recording: Race, Notice, Race-Notice.', '2026-02-05 02:10:17', NULL),
('310', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, 'DBCD: Duty, Breach, Causation, Damages | Strict: dangerous activities, wild animals, products | BAFTIC: Battery, Assault, False imprisonment, Trespass, IIED, Conversion.', '2026-02-05 02:10:17', NULL),
('311', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, 'DBCD: Duty, Breach, Causation, Damages | Strict: dangerous activities, wild animals, products | BAFTIC: Battery, Assault, False imprisonment, Trespass, IIED, Conversion.', '2026-02-05 02:10:17', NULL),
('312', 'D', 'Incorrect.', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', NULL, 'DBCD: Duty, Breach, Causation, Damages | Strict: dangerous activities, wild animals, products | BAFTIC: Battery, Assault, False imprisonment, Trespass, IIED, Conversion.', '2026-02-05 02:10:17', NULL),
('313', 'B', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', NULL, 'DBCD: Duty, Breach, Causation, Damages | Strict: dangerous activities, wild animals, products | BAFTIC: Battery, Assault, False imprisonment, Trespass, IIED, Conversion.', '2026-02-05 02:10:17', NULL),
('314', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, 'DBCD: Duty, Breach, Causation, Damages | Strict: dangerous activities, wild animals, products | BAFTIC: Battery, Assault, False imprisonment, Trespass, IIED, Conversion.', '2026-02-05 02:10:17', NULL),
('315', 'C', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', NULL, 'DBCD: Duty, Breach, Causation, Damages | Strict: dangerous activities, wild animals, products | BAFTIC: Battery, Assault, False imprisonment, Trespass, IIED, Conversion.', '2026-02-05 02:10:17', NULL),
('316', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, 'DBCD: Duty, Breach, Causation, Damages | Strict: dangerous activities, wild animals, products | BAFTIC: Battery, Assault, False imprisonment, Trespass, IIED, Conversion.', '2026-02-05 02:10:17', NULL)
ON CONFLICT (question_id) DO NOTHING;
