INSERT INTO question_explanations (question_id, correct_answer, choice_a_explanation, choice_b_explanation, choice_c_explanation, choice_d_explanation, subtopic, ai_explanation, created_at, updated_at)
VALUES
('17', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL),
('18', 'B', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', NULL, 'Elements: Actus reus + Mens rea + Causation + Concurrence | BARRK: Burglary, Arson, Robbery, Rape, Kidnapping | Mens rea: Purpose > Knowledge > Recklessness > Negligence.', '2026-02-05 02:10:17', NULL),
('19', 'B', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL),
('20', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, 'Estates: Fee simple > Defeasible > Life | Future: Reversion (grantor), Remainder (3rd party) | Recording: Race, Notice, Race-Notice.', '2026-02-05 02:10:17', NULL),
('21', 'B', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', NULL, 'Estates: Fee simple > Defeasible > Life | Future: Reversion (grantor), Remainder (3rd party) | Recording: Race, Notice, Race-Notice.', '2026-02-05 02:10:17', NULL),
('22', 'D', 'Incorrect.', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', NULL, 'Estates: Fee simple > Defeasible > Life | Future: Reversion (grantor), Remainder (3rd party) | Recording: Race, Notice, Race-Notice.', '2026-02-05 02:10:17', NULL),
('23', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, 'Estates: Fee simple > Defeasible > Life | Future: Reversion (grantor), Remainder (3rd party) | Recording: Race, Notice, Race-Notice.', '2026-02-05 02:10:17', NULL),
('24', 'B', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', NULL, 'Estates: Fee simple > Defeasible > Life | Future: Reversion (grantor), Remainder (3rd party) | Recording: Race, Notice, Race-Notice.', '2026-02-05 02:10:17', NULL),
('25', 'D', 'Incorrect.', 'Incorrect.', 'Incorrect.', 'CORRECT. Properly applies the legal rule.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL),
('26', 'A', 'CORRECT. Properly applies the legal rule.', 'Incorrect.', 'Incorrect.', 'Incorrect.', NULL, 'OACK: Offer + Acceptance + Consideration + No Defenses | MY LEGS for SOF: Marriage, Year+, Land, Executor, Goods $500+, Surety | Mailbox: acceptance on dispatch.', '2026-02-05 02:10:17', NULL)
ON CONFLICT (question_id) DO NOTHING;
